# -*- coding: utf-8 -*-
"""churn_labeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_NSndUnVteZZM4-4OB-t-P5PEai9eBK

Imports
"""

import pandas as pd
import numpy as np

"""Load Dataset"""

customer_level_dataset = pd.read_csv("/content/customer_level_dataset.csv")

customer_level_dataset["order_purchase_timestamp"] = pd.to_datetime(customer_level_dataset["order_purchase_timestamp"])

print(customer_level_dataset.shape)
customer_level_dataset.head()

"""Sort Customer Timeline"""

customer_level_dataset = customer_level_dataset.sort_values(["customer_unique_id","order_purchase_timestamp"])

customer_level_dataset.head()

print(customer_level_dataset.shape)

print(customer_level_dataset["customer_unique_id"].nunique())

"""Create First Purchase Date"""

first_purchase = (customer_level_dataset.groupby("customer_unique_id")["order_purchase_timestamp"].min().reset_index().rename(columns={"order_purchase_timestamp":first_purchase_date"}))

first_purchase.head()

print(first_purchase.shape)

print(first_purchase["customer_unique_id"].nunique())

"""Merge First Purchase Date"""

customer_level_dataset = customer_level_dataset.merge(first_purchase,on="customer_unique_id",how="left")

print(customer_level_dataset.shape)

"""Days Since First Purchase"""

customer_level_dataset["days_from_first_purchase"] = (customer_level_dataset["order_purchase_timestamp"]-customer_level_dataset["first_purchase_date"]).dt.days

customer_level_dataset[["customer_unique_id","days_from_first_purchase"]].head()

"""Identify Repeat Purchases Within 90 Days"""

repeat_within_90 = (customer_level_dataset[customer_level_dataset["days_from_first_purchase"].between(1, 90)].groupby("customer_unique_id").size().reset_index(name="repeat_orders_90d"))

repeat_within_90.head()

"""Create Churn Labels"""

customer_churn = first_purchase.merge(repeat_within_90,on="customer_unique_id",how="left")

customer_churn["repeat_orders_90d"] = (customer_churn["repeat_orders_90d"].fillna(0))

customer_churn["churn_label"] = np.where(customer_churn["repeat_orders_90d"] > 0,0,1)

customer_churn.head()

"""Label Distribution"""

label_counts = (customer_churn["churn_label"].value_counts())

print(label_counts)

print("\nPercentages:")

print(customer_churn["churn_label"].value_counts(normalize=True)* 100)

"""Merge Labels Back"""

customer_churn_dataset = (customer_level_dataset.merge(customer_churn[["customer_unique_id","churn_label"]],on="customer_unique_id",how="left"))

print(customer_churn_dataset.shape)

"""Save Output"""

OUTPUT_FILE = "customer_churn_dataset.csv"

customer_churn_dataset.to_csv(OUTPUT_FILE,index=False)

print(f"Saved: {OUTPUT_FILE}")

"""Final Validation"""

print(f"Dataset Shape: " f"{customer_churn_dataset.shape}")

print("\nUnique Customers:")

print(customer_churn_dataset["customer_unique_id"].nunique())

print("\nChurn Distribution:")

print(customer_churn_dataset["churn_label"].value_counts())

print("\nChurn Percentage:")

print(customer_churn_dataset["churn_label"].value_counts(normalize=True)* 100)