# -*- coding: utf-8 -*-
"""data_preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BiRNoPGlpBau7MXo3hWFI6UTBq_fHrzK

IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np

"""LOAD DATASETS"""

customers = pd.read_csv('/content/olist_customers_dataset.csv')
orders = pd.read_csv('/content/olist_orders_dataset.csv')
order_items = pd.read_csv('/content/olist_order_items_dataset.csv')
payments = pd.read_csv('/content/olist_order_payments_dataset.csv')
reviews = pd.read_csv('/content/olist_order_reviews_dataset.csv')
sellers = pd.read_csv('/content/olist_sellers_dataset.csv')

"""DATASET SHAPES"""

print("\nDataset Shapes:")

print(f"Customers: {customers.shape}")
print(f"Orders: {orders.shape}")
print(f"Order Items: {order_items.shape}")
print(f"Payments: {payments.shape}")
print(f"Reviews: {reviews.shape}")
print(f"Sellers: {sellers.shape}")

"""CLEAN NULLS & TIMESTAMPS"""

# Replace empty strings with NaN
orders = orders.replace("", np.nan)

timestamp_columns = ["order_purchase_timestamp","order_approved_at",
    "order_delivered_carrier_date","order_delivered_customer_date",
    "order_estimated_delivery_date"]

# Convert timestamps
for col in timestamp_columns:

    orders[col] = pd.to_datetime(orders[col],errors="coerce")

"""REMOVE INVALID LIFECYCLE ROWS"""

orders = orders[~((orders["order_delivered_customer_date"].notnull())&(orders["order_delivered_carrier_date"].notnull())&(orders["order_delivered_customer_date"]<orders["order_delivered_carrier_date"]))]

"""CREATE DELIVERY FEATURES"""

print("\nCreating delivery features...")

orders["delivery_days"] = (orders["order_delivered_customer_date"]-orders["order_purchase_timestamp"]).dt.days

orders["estimated_delivery_days"] = (orders["order_estimated_delivery_date"]-orders["order_purchase_timestamp"]).dt.days

# Late delivery flag

orders["is_late_delivery"] = np.where(orders["order_delivered_customer_date"]>orders["order_estimated_delivery_date"],1,0)

"""AGGREGATE PAYMENT DATA"""

payments_agg = (payments.groupby("order_id", as_index=False).agg({"payment_value": "sum"}))

payments_agg.rename(columns={"payment_value": "total_payment_value"},inplace=True)

"""AGGREGATE REVIEW DATA"""

reviews_agg = (reviews.groupby("order_id", as_index=False).agg({"review_score": "mean"}))

"""AGGREGATE ORDER ITEMS"""

# Total item value

order_items["total_item_value"] = (order_items["price"]+order_items["freight_value"])

order_items_agg = (order_items.groupby("order_id", as_index=False).agg({"order_item_id": "count","price": "sum","freight_value": "sum","total_item_value": "sum",
        # Most frequent seller per order
        "seller_id": lambda x: (
            x.mode()[0]
            if not x.mode().empty
            else np.nan
        )}))

order_items_agg.rename(
    columns={"order_item_id": "total_items","price": "total_price","freight_value": "total_freight"},inplace=True)

"""MERGE DATASETS"""

# Orders + Customers

merged_df = orders.merge(customers,on="customer_id",how="left")

# Add aggregated order items

merged_df = merged_df.merge(order_items_agg,on="order_id",how="left")

# Add payments

merged_df = merged_df.merge(payments_agg,on="order_id",how="left")

# Add reviews

merged_df = merged_df.merge(reviews_agg,on="order_id",how="left")

"""ADD SELLER INFORMATION"""

seller_info = sellers[["seller_id","seller_state"]]

merged_df = merged_df.merge(seller_info,on="seller_id",how="left")

"""SORT CUSTOMER TIMELINE"""

merged_df = merged_df.sort_values(by=["customer_unique_id","order_purchase_timestamp"])

"""SELECT FINAL COLUMNS"""

final_columns = [

    # Customer Information
    "customer_id",
    "customer_unique_id",
    "customer_city",
    "customer_state",

    # Order Information
    "order_id",
    "order_status",
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",

    # Revenue Features
    "total_price",
    "total_freight",
    "total_item_value",
    "total_payment_value",

    # Delivery Features
    "delivery_days",
    "estimated_delivery_days",
    "is_late_delivery",

    # Review Features
    "review_score",

    # Seller Features
    "seller_id",
    "seller_state",

    # Item Features
    "total_items"
]

customer_level_dataset = merged_df[final_columns]

"""HANDLE NULL VALUES"""

numeric_columns = ["total_price","total_freight","total_item_value","total_payment_value","delivery_days","estimated_delivery_days","review_score","total_items"]

for col in numeric_columns:
  customer_level_dataset[col] = (customer_level_dataset[col].fillna(0))

"""SAVE OUTPUT"""

print(customer_level_dataset.shape)

OUTPUT_FILE = "customer_level_dataset.csv"

customer_level_dataset.to_csv(OUTPUT_FILE,index=False)

print(f"\nFinal Dataset Shape: {customer_level_dataset.shape}")

print("\nTotal Unique Customers:")
print(customer_level_dataset["customer_unique_id"].nunique())

print("\nTotal Orders:")
print(customer_level_dataset["order_id"].nunique())

print("\nDate Range:")

print(customer_level_dataset["order_purchase_timestamp"].min(),"to",customer_level_dataset["order_purchase_timestamp"].max())

print("\nMissing Values:")

missing_values = (customer_level_dataset.isnull().sum())

print(missing_values[missing_values > 0])

print("\nColumn List:")
print(customer_level_dataset.columns.tolist())

print("\nDataset Preview:")
display(customer_level_dataset.head())

print(customer_level_dataset["customer_unique_id"].duplicated().sum())