# -*- coding: utf-8 -*-
"""feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEJipz_4YN2taAjT4-D9ABHL-GMmEdCz

Imports
"""

import pandas as pd
import numpy as np

"""Load Dataset"""

customer_churn_dataset = pd.read_csv("customer_churn_dataset.csv")

date_columns = ["order_purchase_timestamp", "order_approved_at","order_delivered_carrier_date","order_delivered_customer_date","order_estimated_delivery_date","first_purchase_date"]

for col in date_columns:
    customer_churn_dataset[col] = pd.to_datetime(customer_churn_dataset[col],errors="coerce")

print(customer_churn_dataset.shape)
customer_churn_dataset.head()

"""Reference Date for Recency"""

reference_date = customer_churn_dataset["order_purchase_timestamp"].max()

print("Reference Date:")
print(reference_date)

"""Behavioral Features"""

behavioral_features = customer_churn_dataset.groupby("customer_unique_id").agg(total_orders=("order_id","nunique"),total_spend=("total_payment_value","sum"),avg_order_value=("total_payment_value","mean"),avg_delivery_days=("delivery_days","mean")).reset_index()

print(behavioral_features.shape)
behavioral_features.head()

"""RFM Features"""

rfm_features = customer_churn_dataset.groupby("customer_unique_id").agg(last_purchase_date=("order_purchase_timestamp","max"),frequency=("order_id","nunique"),monetary=("total_payment_value","sum")).reset_index()

rfm_features["recency"] = (reference_date - rfm_features["last_purchase_date"]).dt.days
rfm_features.drop("last_purchase_date",axis=1,inplace=True)

print(rfm_features.shape)
rfm_features.head()

"""Operational Features"""

operational_features = customer_churn_dataset.groupby("customer_unique_id").agg(late_delivery_ratio=("is_late_delivery","mean"),avg_review_score=("review_score","mean")).reset_index()

print(operational_features.shape)
operational_features.head()

"""Geographic Features"""

geo_features = customer_churn_dataset.groupby("customer_unique_id").agg(
    customer_state=("customer_state",lambda x: x.mode()[0]),
    seller_state=("seller_state",
                  lambda x: x.mode()[0]
                  if len(x.mode()) > 0
                  else "Unknown")).reset_index()

print(geo_features.shape)
geo_features.head()

"""Churn Labels"""

labels = customer_churn_dataset.groupby("customer_unique_id").agg(churn_label=("churn_label","max")).reset_index()

print(labels.shape)
labels.head()

"""Merge Everything"""

ml_feature_dataset = behavioral_features.merge(rfm_features,on="customer_unique_id",how="left")

ml_feature_dataset = ml_feature_dataset.merge(operational_features,on="customer_unique_id",how="left")

ml_feature_dataset = ml_feature_dataset.merge(geo_features,on="customer_unique_id",how="left")

ml_feature_dataset = ml_feature_dataset.merge(labels,on="customer_unique_id",how="left")

print(ml_feature_dataset.shape)
ml_feature_dataset.head()

"""Missing Values"""

numeric_columns = ["avg_delivery_days","late_delivery_ratio","avg_review_score"]

for col in numeric_columns:
    ml_feature_dataset[col] = ml_feature_dataset[col].fillna(0)

ml_feature_dataset["seller_state"] = (ml_feature_dataset["seller_state"].fillna("Unknown"))

print(ml_feature_dataset.isnull().sum().sum())

"""Validation"""

print("Dataset Shape:")
print(ml_feature_dataset.shape)

print("\nColumns:")
print(ml_feature_dataset.columns.tolist())

print("\nTarget Distribution:")
print(ml_feature_dataset["churn_label"].value_counts())

print("\nTarget Percentage:")
print(ml_feature_dataset["churn_label"].value_counts(normalize=True) * 100)

"""Save Dataset"""

ml_feature_dataset.to_csv("ml_feature_dataset.csv",index=False)

"""Final Summary"""

print("Final Shape:")
print(ml_feature_dataset.shape)

print("\nUnique Customers:")
print(ml_feature_dataset["customer_unique_id"].nunique())

print("\nFeature Count:")
print(len(ml_feature_dataset.columns))

print("\nChurn Distribution:")
print(ml_feature_dataset["churn_label"].value_counts())